
import java.util.Date;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Almas Asghar
 */
public class Attendance_Form extends javax.swing.JFrame {

    AttendanceCtrl ad;
    public Attendance_Form() {
        initComponents();
        ad=new AttendanceCtrl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Student_pan = new javax.swing.JPanel();
        attndnce_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attndnce_table = new javax.swing.JTable();
        clear = new javax.swing.JButton();
        back_btn1 = new javax.swing.JButton();
        Logout_btn3 = new javax.swing.JButton();
        View_btn = new javax.swing.JButton();
        valid = new javax.swing.JLabel();
        Update_btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student_Information");
        setName("std_frame"); // NOI18N
        setResizable(false);

        Student_pan.setBackground(new java.awt.Color(0, 204, 204));
        Student_pan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));
        Student_pan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        attndnce_title.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        attndnce_title.setText("Employee Attendance Page");

        attndnce_table.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        attndnce_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "emp_id", "emp_name", "month", "day_1", "day_2", "day_3", "day_4", "day_5", "day_6", "day_7", "day_8", "day_9", "day_10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attndnce_table.setRowHeight(20);
        attndnce_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attndnce_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(attndnce_table);

        clear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        clear.setText("Clear");
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        back_btn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        back_btn1.setText("Back");
        back_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        Logout_btn3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Logout_btn3.setText("Logout");
        Logout_btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Logout_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btn3ActionPerformed(evt);
            }
        });

        View_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        View_btn.setText("View Info");
        View_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        View_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_btnActionPerformed(evt);
            }
        });

        valid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        valid.setForeground(new java.awt.Color(255, 0, 0));

        Update_btn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Update_btn1.setText("Update Info");
        Update_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Update_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Student_panLayout = new javax.swing.GroupLayout(Student_pan);
        Student_pan.setLayout(Student_panLayout);
        Student_panLayout.setHorizontalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(attndnce_title, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Student_panLayout.setVerticalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(attndnce_title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Update_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
       ad.BackPage();
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void Logout_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btn3ActionPerformed
        ad.LogOut();
    }//GEN-LAST:event_Logout_btn3ActionPerformed

    private void View_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_btnActionPerformed
        ad.ViewTableData();
    }//GEN-LAST:event_View_btnActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        ad.ClearTable();
    }//GEN-LAST:event_clearActionPerformed

    private void attndnce_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attndnce_tableMouseClicked
       // m.FillDataInFields();
    }//GEN-LAST:event_attndnce_tableMouseClicked

    private void Update_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btn1ActionPerformed
        ad.UpdateData();
    }//GEN-LAST:event_Update_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout_btn3;
    private javax.swing.JPanel Student_pan;
    javax.swing.JButton Update_btn1;
    private javax.swing.JButton View_btn;
    javax.swing.JTable attndnce_table;
    private javax.swing.JLabel attndnce_title;
    private javax.swing.JButton back_btn1;
    javax.swing.JButton clear;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JLabel valid;
    // End of variables declaration//GEN-END:variables
}
