/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Almas Asghar
 */
public class Fee_Form extends javax.swing.JFrame {

   FeeCtrl f;
   StudentCtrl st;
    public Fee_Form(StudentCtrl stt) {
        initComponents();
        f=new FeeCtrl(this);
        st=stt;
        f.ValueInCombsobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Student_pan = new javax.swing.JPanel();
        fee_title = new javax.swing.JLabel();
        mess_exp = new javax.swing.JLabel();
        utility_bills = new javax.swing.JLabel();
        room_fee = new javax.swing.JLabel();
        fee_status = new javax.swing.JLabel();
        std_name = new javax.swing.JLabel();
        std_id = new javax.swing.JLabel();
        tf_utility_bills = new javax.swing.JTextField();
        tf_room_fee = new javax.swing.JTextField();
        tf_std_name = new javax.swing.JTextField();
        tf_mess_exp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fee_table = new javax.swing.JTable();
        Update_btn = new javax.swing.JButton();
        back_btn1 = new javax.swing.JButton();
        Add_btn2 = new javax.swing.JButton();
        Logout_btn3 = new javax.swing.JButton();
        Reset_btn6 = new javax.swing.JButton();
        delet_btn2 = new javax.swing.JButton();
        valid = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        View_btn = new javax.swing.JButton();
        Add_btn5 = new javax.swing.JButton();
        tf_std_id = new javax.swing.JComboBox();
        tf_fee_status = new javax.swing.JTextField();
        ClearT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student_Information");
        setName("std_frame"); // NOI18N
        setResizable(false);

        Student_pan.setBackground(new java.awt.Color(0, 204, 204));
        Student_pan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));
        Student_pan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        fee_title.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        fee_title.setText("Fee Information Page");

        mess_exp.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        mess_exp.setText("Mess Fee");

        utility_bills.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        utility_bills.setText("Utility Bills");

        room_fee.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        room_fee.setText("Room Fee");

        fee_status.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        fee_status.setText("Fee Status");

        std_name.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_name.setText("Student Name");

        std_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_id.setText("Student Id");

        tf_utility_bills.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_utility_bills.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_utility_bills.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_utility_billsKeyPressed(evt);
            }
        });

        tf_room_fee.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_room_fee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_room_fee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_room_feeKeyPressed(evt);
            }
        });

        tf_std_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_std_nameActionPerformed(evt);
            }
        });
        tf_std_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_std_nameKeyPressed(evt);
            }
        });

        tf_mess_exp.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_mess_exp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_mess_exp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_mess_expKeyPressed(evt);
            }
        });

        fee_table.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        fee_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Std_id", "Std_name", "Mess_fee", "Utility_Bills", "Room_Fee", "Total_Fee", "Fee_Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fee_table.setRowHeight(20);
        fee_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fee_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fee_table);

        Update_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Update_btn.setText("Update Info");
        Update_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        back_btn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        back_btn1.setText("Back");
        back_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        Add_btn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add_btn2.setText("Add Info");
        Add_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Add_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btn2ActionPerformed(evt);
            }
        });

        Logout_btn3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Logout_btn3.setText("Logout");
        Logout_btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Logout_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btn3ActionPerformed(evt);
            }
        });

        Reset_btn6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Reset_btn6.setText("ResetFields");
        Reset_btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Reset_btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btn6ActionPerformed(evt);
            }
        });

        delet_btn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        delet_btn2.setText("Delete Info");
        delet_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delet_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_btn2ActionPerformed(evt);
            }
        });

        valid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        valid.setForeground(new java.awt.Color(255, 51, 51));

        search.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        View_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        View_btn.setText("View Info");
        View_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        View_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_btnActionPerformed(evt);
            }
        });

        Add_btn5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add_btn5.setText("Search");
        Add_btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Add_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btn5ActionPerformed(evt);
            }
        });

        tf_std_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        tf_std_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_id.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tf_std_idPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        tf_std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_std_idActionPerformed(evt);
            }
        });

        tf_fee_status.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_fee_status.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_fee_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_fee_statusKeyPressed(evt);
            }
        });

        ClearT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ClearT.setText("ClearTable");
        ClearT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ClearT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Student_panLayout = new javax.swing.GroupLayout(Student_pan);
        Student_pan.setLayout(Student_panLayout);
        Student_panLayout.setHorizontalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mess_exp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(utility_bills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(room_fee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fee_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_std_name)
                            .addComponent(tf_room_fee)
                            .addComponent(tf_utility_bills)
                            .addComponent(tf_mess_exp)
                            .addComponent(tf_fee_status)
                            .addComponent(tf_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(Add_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(Update_btn)
                        .addGap(60, 60, 60)
                        .addComponent(Reset_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(delet_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Student_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fee_title, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(423, 423, 423))
        );
        Student_panLayout.setVerticalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(fee_title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_id)
                            .addComponent(tf_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_name)
                            .addComponent(tf_std_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mess_exp)
                            .addComponent(tf_mess_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Student_panLayout.createSequentialGroup()
                                .addComponent(utility_bills)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(room_fee)
                                    .addComponent(tf_room_fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tf_utility_bills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fee_status)
                            .addComponent(tf_fee_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delet_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_std_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_std_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_std_nameActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
      f.BackPage();
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void Logout_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btn3ActionPerformed
       f.LogOut();
    }//GEN-LAST:event_Logout_btn3ActionPerformed

    private void Reset_btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btn6ActionPerformed
        f.Reset();
    }//GEN-LAST:event_Reset_btn6ActionPerformed

    private void Add_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btn5ActionPerformed
        //f.Search();
        f.SearchData();
    }//GEN-LAST:event_Add_btn5ActionPerformed

    private void View_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_btnActionPerformed
        f.ViewTableData();
    }//GEN-LAST:event_View_btnActionPerformed

    private void Add_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btn2ActionPerformed
        f.InsertData();
    }//GEN-LAST:event_Add_btn2ActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
       f.UpdateData();
    }//GEN-LAST:event_Update_btnActionPerformed

    private void delet_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_btn2ActionPerformed
       f.DeleteData();
    }//GEN-LAST:event_delet_btn2ActionPerformed

    private void fee_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fee_tableMouseClicked
      // f.FillDataInFields();
    }//GEN-LAST:event_fee_tableMouseClicked

    private void tf_mess_expKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_mess_expKeyPressed
       f.NumberValidation(evt);
    }//GEN-LAST:event_tf_mess_expKeyPressed

    private void tf_utility_billsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_utility_billsKeyPressed
       f.NumberValidation(evt);
    }//GEN-LAST:event_tf_utility_billsKeyPressed

    private void tf_room_feeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_room_feeKeyPressed
       f.NumberValidation(evt);
    }//GEN-LAST:event_tf_room_feeKeyPressed

    private void tf_std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_std_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_std_idActionPerformed

    private void tf_std_idPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tf_std_idPopupMenuWillBecomeInvisible
        f.SelectValueDataInCb();
    }//GEN-LAST:event_tf_std_idPopupMenuWillBecomeInvisible

    private void tf_fee_statusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_fee_statusKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fee_statusKeyPressed

    private void ClearTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTActionPerformed
        f.ClearTable();                                                        // TODO add your handling code here:
    }//GEN-LAST:event_ClearTActionPerformed

    private void tf_std_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_std_nameKeyPressed
       f.CharValidation(evt);
    }//GEN-LAST:event_tf_std_nameKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn2;
    private javax.swing.JButton Add_btn5;
    private javax.swing.JButton ClearT;
    private javax.swing.JButton Logout_btn3;
    private javax.swing.JButton Reset_btn6;
    private javax.swing.JPanel Student_pan;
    private javax.swing.JButton Update_btn;
    private javax.swing.JButton View_btn;
    private javax.swing.JButton back_btn1;
    private javax.swing.JButton delet_btn2;
    private javax.swing.JLabel fee_status;
    javax.swing.JTable fee_table;
    private javax.swing.JLabel fee_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mess_exp;
    private javax.swing.JLabel room_fee;
    javax.swing.JTextField search;
    private javax.swing.JLabel std_id;
    private javax.swing.JLabel std_name;
    javax.swing.JTextField tf_fee_status;
    javax.swing.JTextField tf_mess_exp;
    javax.swing.JTextField tf_room_fee;
    javax.swing.JComboBox tf_std_id;
    javax.swing.JTextField tf_std_name;
    javax.swing.JTextField tf_utility_bills;
    private javax.swing.JLabel utility_bills;
    javax.swing.JLabel valid;
    // End of variables declaration//GEN-END:variables
    public String status;
    
}
