import java.util.Date;
import java.util.Calendar;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Almas Asghar
 */
public class Mess_Form extends javax.swing.JFrame {

    MessCtrl m;
    public Mess_Form() {
        initComponents();
       m=new MessCtrl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Student_pan = new javax.swing.JPanel();
        mess_title = new javax.swing.JLabel();
        mess_expenses = new javax.swing.JLabel();
        mess_bf_time = new javax.swing.JLabel();
        mess_luch_time = new javax.swing.JLabel();
        mess_diner_time = new javax.swing.JLabel();
        sun_bf_time = new javax.swing.JLabel();
        std_hstl_id = new javax.swing.JLabel();
        incharge_id = new javax.swing.JLabel();
        tf_incharge_id = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        tf_hstl_id = new javax.swing.JTextField();
        tf_mess_expnses = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mess_table = new javax.swing.JTable();
        Update_btn = new javax.swing.JButton();
        back_btn1 = new javax.swing.JButton();
        Add_btn2 = new javax.swing.JButton();
        Logout_btn3 = new javax.swing.JButton();
        Reset_btn6 = new javax.swing.JButton();
        delet_btn2 = new javax.swing.JButton();
        Search_btn = new javax.swing.JButton();
        View_btn = new javax.swing.JButton();
        valid = new javax.swing.JLabel();
        tf_bf_time = new javax.swing.JTextField();
        tf_ln_time = new javax.swing.JTextField();
        tf_dn_time = new javax.swing.JTextField();
        tf_sbf_time = new javax.swing.JTextField();
        ClearT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student_Information");
        setName("std_frame"); // NOI18N
        setResizable(false);

        Student_pan.setBackground(new java.awt.Color(0, 204, 204));
        Student_pan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));
        Student_pan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        mess_title.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        mess_title.setText("Mess Information Page");

        mess_expenses.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        mess_expenses.setText("Monthy Avg Exp");

        mess_bf_time.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        mess_bf_time.setText("Mess bf Time");

        mess_luch_time.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        mess_luch_time.setText("Mess Luch Time");

        mess_diner_time.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        mess_diner_time.setText("Mess Dinner Time");

        sun_bf_time.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sun_bf_time.setText("Sunday bf Time");

        std_hstl_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_hstl_id.setText("Hostel Id");

        incharge_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        incharge_id.setText("Incharge Id");

        tf_incharge_id.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_incharge_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        search.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tf_hstl_id.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_hstl_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_hstl_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hstl_idActionPerformed(evt);
            }
        });

        tf_mess_expnses.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_mess_expnses.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_mess_expnses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_mess_expnsesKeyPressed(evt);
            }
        });

        mess_table.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        mess_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Incharge_id", "Hostel_id", "Mon_Avg_Exp", "Mess_Bf_Time", "Mess_lunch_Time", "Mess_Diner_Time", "Sun_Bf_Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mess_table.setRowHeight(20);
        mess_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mess_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mess_table);

        Update_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Update_btn.setText("Update Info");
        Update_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        back_btn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        back_btn1.setText("Back");
        back_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        Add_btn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add_btn2.setText("Add Info");
        Add_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Add_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btn2ActionPerformed(evt);
            }
        });

        Logout_btn3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Logout_btn3.setText("Logout");
        Logout_btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Logout_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btn3ActionPerformed(evt);
            }
        });

        Reset_btn6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Reset_btn6.setText("ResetFields");
        Reset_btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Reset_btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btn6ActionPerformed(evt);
            }
        });

        delet_btn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        delet_btn2.setText("Delete Info");
        delet_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delet_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_btn2ActionPerformed(evt);
            }
        });

        Search_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Search_btn.setText("Search");
        Search_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });

        View_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        View_btn.setText("View Info");
        View_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        View_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_btnActionPerformed(evt);
            }
        });

        valid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        valid.setForeground(new java.awt.Color(255, 0, 0));

        tf_bf_time.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_bf_time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_bf_time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_bf_timeKeyPressed(evt);
            }
        });

        tf_ln_time.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_ln_time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_ln_time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_ln_timeKeyPressed(evt);
            }
        });

        tf_dn_time.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_dn_time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_dn_time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_dn_timeKeyPressed(evt);
            }
        });

        tf_sbf_time.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_sbf_time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_sbf_time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_sbf_timeKeyPressed(evt);
            }
        });

        ClearT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ClearT.setText("ClearTable");
        ClearT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ClearT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Student_panLayout = new javax.swing.GroupLayout(Student_pan);
        Student_pan.setLayout(Student_panLayout);
        Student_panLayout.setHorizontalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Student_panLayout.createSequentialGroup()
                                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mess_expenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mess_bf_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mess_luch_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mess_diner_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sun_bf_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(std_hstl_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(incharge_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Add_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Student_panLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_incharge_id, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(tf_hstl_id)
                                            .addComponent(tf_mess_expnses)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Student_panLayout.createSequentialGroup()
                                                .addComponent(Search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20))
                                            .addComponent(tf_sbf_time)
                                            .addComponent(tf_dn_time, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_ln_time, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_bf_time, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(Student_panLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))
                    .addComponent(valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(Reset_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(delet_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Student_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mess_title, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(423, 423, 423))
        );
        Student_panLayout.setVerticalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(mess_title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incharge_id)
                            .addComponent(tf_incharge_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_hstl_id)
                            .addComponent(tf_hstl_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mess_expenses)
                            .addComponent(tf_mess_expnses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mess_bf_time)
                            .addComponent(tf_bf_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mess_luch_time)
                            .addComponent(tf_ln_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mess_diner_time)
                            .addComponent(tf_dn_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sun_bf_time)
                            .addComponent(tf_sbf_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delet_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reset_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_hstl_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hstl_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hstl_idActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
       m.BackPage();
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void Logout_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btn3ActionPerformed
        m.LogOut();
    }//GEN-LAST:event_Logout_btn3ActionPerformed

    private void Add_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btn2ActionPerformed
        m.InsertData();
    }//GEN-LAST:event_Add_btn2ActionPerformed

    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
        //m.Search();
        m.SearchTable();
    }//GEN-LAST:event_Search_btnActionPerformed

    private void View_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_btnActionPerformed
        m.ViewTableData();
    }//GEN-LAST:event_View_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
       m.UpdateData();
    }//GEN-LAST:event_Update_btnActionPerformed

    private void delet_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_btn2ActionPerformed
       m.DeleteData();
    }//GEN-LAST:event_delet_btn2ActionPerformed

    private void Reset_btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btn6ActionPerformed
       m.Reset();
    }//GEN-LAST:event_Reset_btn6ActionPerformed

    private void tf_mess_expnsesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_mess_expnsesKeyPressed
       m.NumberValidation(evt);
    }//GEN-LAST:event_tf_mess_expnsesKeyPressed

    private void mess_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mess_tableMouseClicked
        m.FillDataInFields();
    }//GEN-LAST:event_mess_tableMouseClicked

    private void tf_bf_timeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_bf_timeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bf_timeKeyPressed

    private void tf_ln_timeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ln_timeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ln_timeKeyPressed

    private void tf_dn_timeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_dn_timeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dn_timeKeyPressed

    private void tf_sbf_timeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_sbf_timeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sbf_timeKeyPressed

    private void ClearTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTActionPerformed
        m.ClearTable();                                                        // TODO add your handling code here:
    }//GEN-LAST:event_ClearTActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn2;
    private javax.swing.JButton ClearT;
    private javax.swing.JButton Logout_btn3;
    private javax.swing.JButton Reset_btn6;
    private javax.swing.JButton Search_btn;
    private javax.swing.JPanel Student_pan;
    private javax.swing.JButton Update_btn;
    private javax.swing.JButton View_btn;
    private javax.swing.JButton back_btn1;
    private javax.swing.JButton delet_btn2;
    private javax.swing.JLabel incharge_id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mess_bf_time;
    private javax.swing.JLabel mess_diner_time;
    private javax.swing.JLabel mess_expenses;
    private javax.swing.JLabel mess_luch_time;
    javax.swing.JTable mess_table;
    private javax.swing.JLabel mess_title;
    javax.swing.JTextField search;
    private javax.swing.JLabel std_hstl_id;
    private javax.swing.JLabel sun_bf_time;
    javax.swing.JTextField tf_bf_time;
    javax.swing.JTextField tf_dn_time;
    javax.swing.JTextField tf_hstl_id;
    javax.swing.JTextField tf_incharge_id;
    javax.swing.JTextField tf_ln_time;
    javax.swing.JTextField tf_mess_expnses;
    javax.swing.JTextField tf_sbf_time;
    javax.swing.JLabel valid;
    // End of variables declaration//GEN-END:variables
}
