
import java.awt.TextField;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Almas Asghar
 */
public class Student_Form extends javax.swing.JFrame {
    StudentCtrl st;
    
    public Student_Form() {
        initComponents();
        st=new StudentCtrl(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Student_pan = new javax.swing.JPanel();
        std_title = new javax.swing.JLabel();
        std_name = new javax.swing.JLabel();
        std_fn = new javax.swing.JLabel();
        std_dpt = new javax.swing.JLabel();
        std_adr = new javax.swing.JLabel();
        std_phn = new javax.swing.JLabel();
        std_dob = new javax.swing.JLabel();
        std_age = new javax.swing.JLabel();
        std_hstl_id = new javax.swing.JLabel();
        std_id = new javax.swing.JLabel();
        tf_std_id = new javax.swing.JTextField();
        tf_std_dept = new javax.swing.JTextField();
        tf_std_addrs = new javax.swing.JTextField();
        tf_std_age = new javax.swing.JTextField();
        tf_hstl_id = new javax.swing.JTextField();
        tf_std_name = new javax.swing.JTextField();
        tf_std_fn = new javax.swing.JTextField();
        tf_phn = new javax.swing.JTextField();
        date = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        std_table = new javax.swing.JTable();
        Update_btn = new javax.swing.JButton();
        back_btn1 = new javax.swing.JButton();
        Add_btn2 = new javax.swing.JButton();
        Logout_btn3 = new javax.swing.JButton();
        Reset_btn6 = new javax.swing.JButton();
        delet_btn2 = new javax.swing.JButton();
        tf_search = new javax.swing.JTextField();
        Add_search = new javax.swing.JButton();
        valid = new javax.swing.JLabel();
        view_btn = new javax.swing.JButton();
        room_Info_btn4 = new javax.swing.JButton();
        fee_Info_btn = new javax.swing.JButton();
        Vst_Info_btn = new javax.swing.JButton();
        ClearT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student_Information");
        setName("std_frame"); // NOI18N
        setResizable(false);

        Student_pan.setBackground(new java.awt.Color(0, 204, 204));
        Student_pan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));
        Student_pan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        std_title.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        std_title.setText("Student Information Page");

        std_name.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_name.setText("Student Name");

        std_fn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_fn.setText("Father Name");

        std_dpt.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_dpt.setText("Department");

        std_adr.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_adr.setText("Address");

        std_phn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_phn.setText("Phone No.");

        std_dob.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_dob.setText("Sudent DOB");

        std_age.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_age.setText("Student Age");

        std_hstl_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_hstl_id.setText("Hostel Id");

        std_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_id.setText("Student Id");

        tf_std_id.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tf_std_dept.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_dept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_std_deptActionPerformed(evt);
            }
        });

        tf_std_addrs.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_addrs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tf_std_age.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_std_ageActionPerformed(evt);
            }
        });
        tf_std_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_std_ageKeyPressed(evt);
            }
        });

        tf_hstl_id.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_hstl_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tf_std_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_std_nameKeyPressed(evt);
            }
        });

        tf_std_fn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_fn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_fn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_std_fnKeyPressed(evt);
            }
        });

        tf_phn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_phn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_phnActionPerformed(evt);
            }
        });
        tf_phn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_phnKeyPressed(evt);
            }
        });

        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        date.setPreferredSize(new java.awt.Dimension(130, 34));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        std_table.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        std_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Std_id", "Std_name", "Father_name", "Department", "Address", "Phone_no", "Std_dob", "Std_age", "Hostel_id", "Room_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        std_table.setGridColor(new java.awt.Color(153, 204, 255));
        std_table.setRowHeight(20);
        std_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                std_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(std_table);

        Update_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Update_btn.setText("Update Info");
        Update_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        back_btn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        back_btn1.setText("Back");
        back_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        Add_btn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add_btn2.setText("Add Info");
        Add_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Add_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btn2ActionPerformed(evt);
            }
        });

        Logout_btn3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Logout_btn3.setText("Logout");
        Logout_btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Logout_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btn3ActionPerformed(evt);
            }
        });

        Reset_btn6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Reset_btn6.setText("Reset ");
        Reset_btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Reset_btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btn6ActionPerformed(evt);
            }
        });

        delet_btn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        delet_btn2.setText("Delete Info");
        delet_btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delet_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_btn2ActionPerformed(evt);
            }
        });

        tf_search.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Add_search.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add_search.setText("Search");
        Add_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Add_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_searchActionPerformed(evt);
            }
        });

        valid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        valid.setForeground(new java.awt.Color(255, 0, 51));

        view_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        view_btn.setText("View Info");
        view_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        room_Info_btn4.setBackground(new java.awt.Color(255, 204, 204));
        room_Info_btn4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        room_Info_btn4.setText("Room");
        room_Info_btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        room_Info_btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_Info_btn4ActionPerformed(evt);
            }
        });

        fee_Info_btn.setBackground(new java.awt.Color(255, 204, 204));
        fee_Info_btn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        fee_Info_btn.setText("Fee");
        fee_Info_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        fee_Info_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fee_Info_btnActionPerformed(evt);
            }
        });

        Vst_Info_btn.setBackground(new java.awt.Color(255, 204, 204));
        Vst_Info_btn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Vst_Info_btn.setText(" Visitors ");
        Vst_Info_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Vst_Info_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vst_Info_btnActionPerformed(evt);
            }
        });

        ClearT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ClearT.setText("ClearTable");
        ClearT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ClearT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Student_panLayout = new javax.swing.GroupLayout(Student_pan);
        Student_pan.setLayout(Student_panLayout);
        Student_panLayout.setHorizontalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(Add_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(Reset_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(std_fn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_dpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_adr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_hstl_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(std_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Student_panLayout.createSequentialGroup()
                                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(std_phn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(std_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(86, 86, 86)))
                        .addGap(18, 18, 18)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_std_id)
                            .addComponent(tf_hstl_id)
                            .addComponent(tf_std_age)
                            .addComponent(tf_std_addrs)
                            .addComponent(tf_std_name)
                            .addComponent(tf_std_fn)
                            .addComponent(tf_phn)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(tf_std_dept, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(Add_search, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(delet_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Student_panLayout.createSequentialGroup()
                                .addComponent(Vst_Info_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(fee_Info_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(room_Info_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Student_panLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(std_title, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(432, 432, 432))
        );
        Student_panLayout.setVerticalGroup(
            Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Student_panLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(std_title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_id)
                            .addComponent(tf_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_name)
                            .addComponent(tf_std_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_fn)
                            .addComponent(tf_std_fn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_dpt)
                            .addComponent(tf_std_dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_adr)
                            .addComponent(tf_std_addrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_phn)
                            .addComponent(tf_phn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_dob)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_age)
                            .addComponent(tf_std_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_hstl_id)
                            .addComponent(tf_hstl_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fee_Info_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(room_Info_btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vst_Info_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(Student_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delet_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reset_btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(Student_panLayout.createSequentialGroup()
                        .addComponent(valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Student_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_std_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_std_ageActionPerformed
       
    }//GEN-LAST:event_tf_std_ageActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
      
    }//GEN-LAST:event_dateActionPerformed

    private void tf_phnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_phnKeyPressed
        st.NumberValidation(evt);
    }//GEN-LAST:event_tf_phnKeyPressed

    private void tf_phnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_phnActionPerformed
        
    }//GEN-LAST:event_tf_phnActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
       st.BackPage();
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void Logout_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btn3ActionPerformed
       st.LogOut();
    }//GEN-LAST:event_Logout_btn3ActionPerformed

    private void Add_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btn2ActionPerformed
       st.InsertInfo();
    }//GEN-LAST:event_Add_btn2ActionPerformed

    private void delet_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_btn2ActionPerformed
       st.DeleteInfo(); 
    }//GEN-LAST:event_delet_btn2ActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
       st.UpdateInfo();
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Add_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_searchActionPerformed
//        st.Search();
        st.SearchTable();
    }//GEN-LAST:event_Add_searchActionPerformed

    private void tf_std_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_std_deptActionPerformed

    }//GEN-LAST:event_tf_std_deptActionPerformed

    private void Reset_btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btn6ActionPerformed
       st.Reset();
    }//GEN-LAST:event_Reset_btn6ActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
        st.ViewTableData();
    }//GEN-LAST:event_view_btnActionPerformed

    private void std_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_std_tableMouseClicked
        st.FillDataInFields();
    }//GEN-LAST:event_std_tableMouseClicked

    private void tf_std_ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_std_ageKeyPressed
        st.NumberValidation(evt);
    }//GEN-LAST:event_tf_std_ageKeyPressed

    private void room_Info_btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_Info_btn4ActionPerformed
        st.OpenAssignRoomForm();
    }//GEN-LAST:event_room_Info_btn4ActionPerformed

    private void fee_Info_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fee_Info_btnActionPerformed
        st.OpenFeeForm();
    }//GEN-LAST:event_fee_Info_btnActionPerformed

    private void Vst_Info_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vst_Info_btnActionPerformed
        st.OpenVisitorsForm();
    }//GEN-LAST:event_Vst_Info_btnActionPerformed

    private void ClearTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTActionPerformed
        st.ClearTable();                                                        // TODO add your handling code here:
    }//GEN-LAST:event_ClearTActionPerformed

    private void tf_std_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_std_nameKeyPressed
        st.CharValidation(evt);
    }//GEN-LAST:event_tf_std_nameKeyPressed

    private void tf_std_fnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_std_fnKeyPressed
        st.CharValidation(evt);
    }//GEN-LAST:event_tf_std_fnKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn2;
    private javax.swing.JButton Add_search;
    private javax.swing.JButton ClearT;
    private javax.swing.JButton Logout_btn3;
    private javax.swing.JButton Reset_btn6;
    private javax.swing.JPanel Student_pan;
    private javax.swing.JButton Update_btn;
    private javax.swing.JButton Vst_Info_btn;
    private javax.swing.JButton back_btn1;
    org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JButton delet_btn2;
    private javax.swing.JButton fee_Info_btn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton room_Info_btn4;
    private javax.swing.JLabel std_adr;
    private javax.swing.JLabel std_age;
    private javax.swing.JLabel std_dob;
    private javax.swing.JLabel std_dpt;
    private javax.swing.JLabel std_fn;
    private javax.swing.JLabel std_hstl_id;
    private javax.swing.JLabel std_id;
    private javax.swing.JLabel std_name;
    private javax.swing.JLabel std_phn;
    javax.swing.JTable std_table;
    private javax.swing.JLabel std_title;
    javax.swing.JTextField tf_hstl_id;
    javax.swing.JTextField tf_phn;
    javax.swing.JTextField tf_search;
    javax.swing.JTextField tf_std_addrs;
    javax.swing.JTextField tf_std_age;
    javax.swing.JTextField tf_std_dept;
    javax.swing.JTextField tf_std_fn;
    javax.swing.JTextField tf_std_id;
    javax.swing.JTextField tf_std_name;
    javax.swing.JLabel valid;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables
}
