
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Almas Asghar
 */
public class Visitors_form extends javax.swing.JFrame {

    VisitorsCtrl vs;
    StudentCtrl st;
    public Visitors_form(StudentCtrl stt) {
        initComponents();
        vs=new VisitorsCtrl(this);
        st=stt;
        vs.ValueInCombsobox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vst_pan = new javax.swing.JPanel();
        vst_title = new javax.swing.JLabel();
        vst_name = new javax.swing.JLabel();
        std_id = new javax.swing.JLabel();
        std_name = new javax.swing.JLabel();
        time_in = new javax.swing.JLabel();
        time_out = new javax.swing.JLabel();
        vst_date = new javax.swing.JLabel();
        vst_id = new javax.swing.JLabel();
        tf_vst_id = new javax.swing.JTextField();
        tf_std_name = new javax.swing.JTextField();
        tf_time_in = new javax.swing.JTextField();
        tf_vst_name = new javax.swing.JTextField();
        tf_time_out = new javax.swing.JTextField();
        date = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        vst_table = new javax.swing.JTable();
        Update_btn = new javax.swing.JButton();
        back_btn1 = new javax.swing.JButton();
        Add_btn = new javax.swing.JButton();
        Logout_btn3 = new javax.swing.JButton();
        Reset_btn = new javax.swing.JButton();
        delet_btn = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        View_btn = new javax.swing.JButton();
        valid = new javax.swing.JLabel();
        tf_std_id = new javax.swing.JComboBox();
        ClearT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visitors_Information");
        setName("emp_frame"); // NOI18N
        setResizable(false);

        vst_pan.setBackground(new java.awt.Color(0, 204, 204));
        vst_pan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 10));
        vst_pan.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        vst_title.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        vst_title.setText("Visitors Information Page");

        vst_name.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        vst_name.setText("Visitor Name");

        std_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_id.setText("Student Id");

        std_name.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        std_name.setText("Student Name");

        time_in.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        time_in.setText("Vst_Time_In");

        time_out.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        time_out.setText("Vst_Time_Out");

        vst_date.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        vst_date.setText("Date");

        vst_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        vst_id.setText("Visitor Id");

        tf_vst_id.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_vst_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tf_std_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_std_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_std_nameKeyPressed(evt);
            }
        });

        tf_time_in.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_time_in.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tf_vst_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_vst_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_vst_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_vst_nameKeyPressed(evt);
            }
        });

        tf_time_out.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        tf_time_out.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_time_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_time_outActionPerformed(evt);
            }
        });
        tf_time_out.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_time_outKeyPressed(evt);
            }
        });

        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        date.setPreferredSize(new java.awt.Dimension(130, 34));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        vst_table.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        vst_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "vst_id", "vst_name", "Std_id", "Std_name", "Time_in", "Time_out", "date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vst_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vst_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vst_table);

        Update_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Update_btn.setText("Update Info");
        Update_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        back_btn1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        back_btn1.setText("Back");
        back_btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        back_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btn1ActionPerformed(evt);
            }
        });

        Add_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Add_btn.setText("Add Info");
        Add_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Logout_btn3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Logout_btn3.setText("Logout");
        Logout_btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Logout_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_btn3ActionPerformed(evt);
            }
        });

        Reset_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Reset_btn.setText("ResetFields");
        Reset_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_btnActionPerformed(evt);
            }
        });

        delet_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        delet_btn.setText("Delete Info");
        delet_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delet_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delet_btnActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        search_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        search_btn.setText("Search");
        search_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        View_btn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        View_btn.setText("View Info");
        View_btn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        View_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_btnActionPerformed(evt);
            }
        });

        valid.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        valid.setForeground(new java.awt.Color(255, 0, 0));

        tf_std_id.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        tf_std_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tf_std_id.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                tf_std_idPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        ClearT.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ClearT.setText("ClearTable");
        ClearT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ClearT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vst_panLayout = new javax.swing.GroupLayout(vst_pan);
        vst_pan.setLayout(vst_panLayout);
        vst_panLayout.setHorizontalGroup(
            vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vst_panLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vst_panLayout.createSequentialGroup()
                        .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(delet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vst_panLayout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(vst_panLayout.createSequentialGroup()
                        .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(vst_panLayout.createSequentialGroup()
                                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(std_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(std_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(time_in, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(time_out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vst_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vst_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vst_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_vst_id)
                                    .addComponent(tf_time_in)
                                    .addComponent(tf_std_name)
                                    .addComponent(tf_vst_name)
                                    .addComponent(tf_time_out)
                                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(tf_std_id, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addComponent(jScrollPane1)))
                .addGap(30, 30, 30))
            .addGroup(vst_panLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(vst_title, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vst_panLayout.setVerticalGroup(
            vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vst_panLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(vst_title, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vst_panLayout.createSequentialGroup()
                        .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vst_id)
                            .addComponent(tf_vst_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vst_name)
                            .addComponent(tf_vst_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(std_id)
                            .addComponent(tf_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vst_panLayout.createSequentialGroup()
                                .addComponent(std_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(time_in)
                                    .addComponent(tf_time_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(time_out)
                                    .addComponent(tf_time_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vst_date)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tf_std_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(valid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(vst_panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delet_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vst_pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vst_pan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void tf_time_outKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_time_outKeyPressed
        try{
            int i=Integer.parseInt(tf_time_out.getText());
           
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_tf_time_outKeyPressed

    private void tf_time_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_time_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_time_outActionPerformed

    private void back_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btn1ActionPerformed
        vs.BackPage();
    }//GEN-LAST:event_back_btn1ActionPerformed

    private void Logout_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_btn3ActionPerformed
        vs.LogOut();
    }//GEN-LAST:event_Logout_btn3ActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        vs.InsertInfo();
    }//GEN-LAST:event_Add_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
       // vs.Search();
        vs.SearchTable();
    }//GEN-LAST:event_search_btnActionPerformed

    private void View_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_btnActionPerformed
        vs.ViewTableData();
    }//GEN-LAST:event_View_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        vs.UpdateInfo();
    }//GEN-LAST:event_Update_btnActionPerformed

    private void delet_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delet_btnActionPerformed
        vs.DeleteInfo();
    }//GEN-LAST:event_delet_btnActionPerformed

    private void Reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_btnActionPerformed
        vs.Reset();
    }//GEN-LAST:event_Reset_btnActionPerformed

    private void vst_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vst_tableMouseClicked
        //vs.FillDataInFields();
    }//GEN-LAST:event_vst_tableMouseClicked

    private void tf_std_idPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_tf_std_idPopupMenuWillBecomeInvisible
        vs.SelectValueDataInCb();
    }//GEN-LAST:event_tf_std_idPopupMenuWillBecomeInvisible

    private void ClearTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTActionPerformed
        vs.ClearTable();                                                        // TODO add your handling code here:
    }//GEN-LAST:event_ClearTActionPerformed

    private void tf_vst_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_vst_nameKeyPressed
        vs.CharValidation(evt);
    }//GEN-LAST:event_tf_vst_nameKeyPressed

    private void tf_std_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_std_nameKeyPressed
        vs.CharValidation(evt);
    }//GEN-LAST:event_tf_std_nameKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton ClearT;
    private javax.swing.JButton Logout_btn3;
    private javax.swing.JButton Reset_btn;
    private javax.swing.JButton Update_btn;
    javax.swing.JButton View_btn;
    private javax.swing.JButton back_btn1;
    org.jdesktop.swingx.JXDatePicker date;
    private javax.swing.JButton delet_btn;
    private javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextField search;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel std_id;
    private javax.swing.JLabel std_name;
    javax.swing.JComboBox tf_std_id;
    javax.swing.JTextField tf_std_name;
    javax.swing.JTextField tf_time_in;
    javax.swing.JTextField tf_time_out;
    javax.swing.JTextField tf_vst_id;
    javax.swing.JTextField tf_vst_name;
    private javax.swing.JLabel time_in;
    private javax.swing.JLabel time_out;
    javax.swing.JLabel valid;
    private javax.swing.JLabel vst_date;
    private javax.swing.JLabel vst_id;
    private javax.swing.JLabel vst_name;
    private javax.swing.JPanel vst_pan;
    javax.swing.JTable vst_table;
    private javax.swing.JLabel vst_title;
    // End of variables declaration//GEN-END:variables
}
